/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor;

import java.awt.Font;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Vikto
 */
public class FontDialog extends javax.swing.JDialog {

    /**
     * Creates new form FontDialog
     * @param parent
     * @param modal
     * @param font
     */
    
    private Font font;
    private String actionButton = "Exit";
    public FontDialog(java.awt.Frame parent, boolean modal, Font font) {
        super(parent, modal);
        this.font = font;
        initComponents();
        String[] fonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        for(String f: fonts){
            BoxFontface.addItem(f);
            if (f.equals(font.getFamily()))
                BoxFontface.setSelectedItem(f);
        }
        BoxBold.setSelected(font.isBold());
        BoxItalic.setSelected(font.isItalic());
        BoxFontSize.getModel().setValue(font.getSize2D());
        TestArea.setFont(font);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BoxFontface = new javax.swing.JComboBox<>();
        BoxBold = new javax.swing.JCheckBox();
        BoxItalic = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BoxFontSize = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        TestArea = new javax.swing.JTextArea();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fontface:");

        BoxFontface.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        BoxFontface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxFontfaceActionPerformed(evt);
            }
        });

        BoxBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxBoldActionPerformed(evt);
            }
        });

        BoxItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxItalicActionPerformed(evt);
            }
        });

        jLabel2.setText("Bold:");

        jLabel3.setText("Italic:");

        jLabel5.setText("Size:");

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BoxFontSize.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        BoxFontSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BoxFontSizeStateChanged(evt);
            }
        });

        TestArea.setEditable(false);
        TestArea.setColumns(20);
        TestArea.setRows(5);
        TestArea.setText("The quick brown fox jumped over the lazy dog.");
        jScrollPane1.setViewportView(TestArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BoxItalic)
                            .addComponent(BoxBold)
                            .addComponent(BoxFontface, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BoxFontSize, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BoxFontface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(BoxFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BoxBold)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxItalic))
                            .addComponent(jLabel3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String showDialog() {
        this.setVisible(true);
        return actionButton;
    }
    
    @Override
    public Font getFont(){
        return this.font;
    }
    
    private void BoxFontfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxFontfaceActionPerformed
        font = new Font((String)BoxFontface.getSelectedItem(),font.getStyle(),font.getSize());
        TestArea.setFont(font);
    }//GEN-LAST:event_BoxFontfaceActionPerformed

    private void BoxBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxBoldActionPerformed
        font = font.deriveFont((BoxBold.isSelected()?Font.BOLD:0)|(font.isItalic()?Font.ITALIC:0));
        TestArea.setFont(font);
    }//GEN-LAST:event_BoxBoldActionPerformed

    private void BoxItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxItalicActionPerformed
        font = font.deriveFont((BoxItalic.isSelected()?Font.ITALIC:0)|(font.isBold()?Font.BOLD:0));
        TestArea.setFont(font);
    }//GEN-LAST:event_BoxItalicActionPerformed

    private void BoxFontSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BoxFontSizeStateChanged
        font = font.deriveFont(font.getStyle(), (float)BoxFontSize.getValue());
        TestArea.setFont(font);
    }//GEN-LAST:event_BoxFontSizeStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actionButton = "Accept";
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actionButton = "Exit";
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BoxBold;
    private javax.swing.JSpinner BoxFontSize;
    private javax.swing.JComboBox<String> BoxFontface;
    private javax.swing.JCheckBox BoxItalic;
    private javax.swing.JTextArea TestArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
