/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vikto
 */
public class ScoreDisplay extends javax.swing.JDialog {

    
    private Connection spojeni;
    private final DefaultTableModel model;
    private final java.awt.Frame parent;
    
    public ScoreDisplay(java.awt.Frame parent, boolean modal, Connection spojeni) {
        super(parent, modal);
        initComponents();
        this.spojeni = spojeni;
        this.parent = parent;
        tabulka.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null,null,null,null,null}
                },
                new String[]{
                    "ID","Jméno","Počet správně","Počet špatně","Počet neodpovězeno"
                }
        ){
             Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        });
        model = (DefaultTableModel) tabulka.getModel();
        listData(getAllRecords());
        this.setVisible(true);
    }
    
    private void listData(ResultSet data) {
        /* Cyklus provede odstranění všech řádků tabulky */
        for (int i = tabulka.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        try {
            /* Cyklus přidává datové řady do tabulky; dokud data.next() nevrátí false (protože už neexistuje žádný další záznam)  */
            while (data.next()) {
                int id = data.getInt(1);
                String jmeno = data.getString("jmeno");
                int pocet_spravne = data.getInt(3);
                int pocet_spatne = data.getInt(4);
                int pocet_neodpovezeno = data.getInt(5);
                
                /* Přidávaný řádek je objektem, který tvoří hodnoty pro jednotlivé sloupce tabulky */
                model.addRow(new Object[]{id, jmeno, pocet_spravne,pocet_spatne,pocet_neodpovezeno});
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Chyba při komunikaci s databází", "Chyba", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private ResultSet getAllRecords() {
        ResultSet vysledky = null;
        try {
            /* Připravený SQL dotaz */
            PreparedStatement dotaz = this.spojeni.prepareStatement("SELECT * FROM skore");
            /* Provedení dotazu a předání výsledků */
            vysledky = dotaz.executeQuery();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Chyba při komunikaci s databází", "Chyba", JOptionPane.ERROR_MESSAGE);
        }
        return vysledky;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabulka = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabulka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabulka);

        jButton1.setText("Zpět");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        parent.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabulka;
    // End of variables declaration//GEN-END:variables
}
