/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elite;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class PortMenu extends javax.swing.JDialog {

    /**
     * Creates new form ShipMenu
     */
    private DefaultListModel model;
    private java.awt.Frame workaround;
    private ArrayList<Port> ports;
    private ArrayList<Ship> ships;
    
    public PortMenu(java.awt.Frame parent, boolean modal,ArrayList<Ship> ships,ArrayList<Port> ports) {
        super(parent, modal);
        initComponents();
        model = new DefaultListModel();
        this.ships = ships;
        this.ports = ports;
        for(Port port : this.ports)
            model.addElement(port);
        jList1.setModel(model);
        workaround = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuAdd = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuDelete = new javax.swing.JMenuItem();
        menuDeleteAll = new javax.swing.JMenuItem();
        buttonExit = new javax.swing.JButton();
        paneShips = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonAdd = new javax.swing.JButton();

        jPopupMenu1.setToolTipText("");
        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuAdd.setText("Add new");
        menuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuAdd);

        menuEdit.setText("Edit");
        menuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEdit);
        jPopupMenu1.add(jSeparator1);

        menuDelete.setText("Delete");
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuDelete);

        menuDeleteAll.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        menuDeleteAll.setText("Delete all");
        menuDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteAllActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuDeleteAll);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ports");

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        jList1.setComponentPopupMenu(jPopupMenu1);
        paneShips.setViewportView(jList1);

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(paneShips, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneShips, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        model.addElement(new Port());
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        ports.clear();
        Port[] helpArray = new Port[model.getSize()];
        model.copyInto(helpArray);
        for (Port port : helpArray)
            ports.add(port);
        dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void menuDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteAllActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Are you sure?","Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)
            model.clear();
        /*int i;
        int x;
        String response;
        for(i=0;;i++){
            response = "Are you";
            for(x=0;x<i;x++)
                response += " really";
            response += " sure?";
            if(JOptionPane.showConfirmDialog(this,response,"Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE) == JOptionPane.NO_OPTION)
                break;
        }*/
    }//GEN-LAST:event_menuDeleteAllActionPerformed

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        int selectedIndex = jList1.getSelectedIndex();
        if(selectedIndex != -1)
            model.remove(selectedIndex);
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void menuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddActionPerformed
        model.addElement(new Port());
    }//GEN-LAST:event_menuAddActionPerformed

    private void menuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditActionPerformed
        PortEdit dialog = new PortEdit(workaround,true,(Port)model.getElementAt(jList1.getSelectedIndex()),ships);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonExit;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuAdd;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuDeleteAll;
    private javax.swing.JMenuItem menuEdit;
    private javax.swing.JScrollPane paneShips;
    // End of variables declaration//GEN-END:variables
}
